# Generated by Django 4.2.6 on 2023-10-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('price', models.FloatField()),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('Availability', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
    ]
